# Generated by Django 5.1.6 on 2025-03-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministries.department')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leader')),
            ],
            options={
                'unique_together': {('leader', 'department')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministries.department')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
            options={
                'unique_together': {('worker', 'department')},
            },
        ),
    ]
