# Generated by Django 5.1.6 on 2025-03-16 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DemographicLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demographic.demographic')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leader')),
            ],
        ),
    ]
